### ISSUE TITLE
Docker运行报错   'ascii' codec can't encode character '\uff1b' in position 351: ordinal not in range(128)

### ISSUE THREAD

**Issue by Mo-Qiong** [Wodlie/AutoMihoyoBBS#4]
mihoyo-bbs_1  | Traceback (most recent call last):
mihoyo-bbs_1  |   File "/var/app/./main_multi.py", line 76, in <module>
mihoyo-bbs_1  |     main_multi(autorun)
mihoyo-bbs_1  |   File "/var/app/./main_multi.py", line 43, in main_multi
mihoyo-bbs_1  |     run_code, run_message = main.main()
mihoyo-bbs_1  |                             ^^^^^^^^^^^
mihoyo-bbs_1  |   File "/var/app/main.py", line 93, in main
mihoyo-bbs_1  |     genshin_help = genshin.Genshin()
mihoyo-bbs_1  |                    ^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/var/app/genshin.py", line 23, in __init__
mihoyo-bbs_1  |     self.account_list = get_account_list("hk4e_cn", self.headers)
mihoyo-bbs_1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/var/app/account.py", line 11, in get_account_list
mihoyo-bbs_1  |     req = http.get(setting.account_Info_url + game_id, headers=headers)
mihoyo-bbs_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1045, in get
mihoyo-bbs_1  |     return self.request(
mihoyo-bbs_1  |            ^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 808, in request
mihoyo-bbs_1  |     request = self.build_request(
mihoyo-bbs_1  |               ^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 349, in build_request
mihoyo-bbs_1  |     headers = self._merge_headers(headers)
mihoyo-bbs_1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 416, in _merge_headers
mihoyo-bbs_1  |     merged_headers.update(headers)
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 200, in update
mihoyo-bbs_1  |     headers = Headers(headers)
mihoyo-bbs_1  |               ^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 71, in __init__
mihoyo-bbs_1  |     self._list = [
mihoyo-bbs_1  |                  ^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 75, in <listcomp>
mihoyo-bbs_1  |     normalize_header_value(v, encoding),
mihoyo-bbs_1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_utils.py", line 55, in normalize_header_value
mihoyo-bbs_1  |     return value.encode(encoding or "ascii")
mihoyo-bbs_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyo-bbs_1  | UnicodeEncodeError: 'ascii' codec can't encode character '\uff1b' in position 351: ordinal not in range(128)

**Comment by Mo-Qiong** [comment]
已解决：粘贴http://user.mihoyo.com的cookie时在最后加了个;[空格]导致报错。
