### ISSUE TITLE
青龙拉取运行时无法找到目录中geetestServer文件

### ISSUE THREAD

**Issue by 2045ga** [Wodlie/AutoMihoyoBBS#8]
按照[README.md](https://github.com/Wodlie/AutoMihoyoBBS/blob/master/README.md)中青龙拉取教程配置后，执行报错

日志报错：
```
## 开始执行... 2023-05-05 00:52:41

Traceback (most recent call last):
  File "/ql/scripts/Wodlie_AutoMihoyoBBS/ql_main.py", line 7, in <module>
    from main import main
  File "/ql/scripts/Wodlie_AutoMihoyoBBS/main.py", line 8, in <module>
    import genshin
  File "/ql/scripts/Wodlie_AutoMihoyoBBS/genshin.py", line 5, in <module>
    import captcha
  File "/ql/scripts/Wodlie_AutoMihoyoBBS/captcha.py", line 1, in <module>
    from geetestServer import GeetestValidateServer
ModuleNotFoundError: No module named 'geetestServer'

## 执行结束... 2023-05-05 00:52:42 耗时 1 秒
```

运行环境：qinglong 2.11.3 和 2.15.11 两个版本都报错

**Comment by love3937** [comment]
我也是这样，不知道怎么解决

**Comment by GomoXU** [comment]
手动下载文件拖到青龙这个程序里边，自动下载的不完整

**Comment by walklty** [comment]
订阅的时候在依赖里面加上geetestServer
